### PR TITLE
Make rcu_domain a concept instead of a polymorphic base class.

### LINKED ISSUE #6: Tests are broken by e9453e1
```
Arthurs-MacBook-Pro-2:Test ajo$ make -k
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test1 dshollman/test1.cpp -pthread -lurcu -lurcu-signal
In file included from dshollman/test1.cpp:1:
In file included from dshollman/rcu_ptr.hpp:7:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:40:16: error: redefinition of 'is_rcu_flavor' as different kind of symbol
constexpr bool is_rcu_flavor = is_rcu_flavor<_T>::value;
               ^
dshollman/rcu_ptr.hpp:32:8: note: previous definition is here
struct is_rcu_flavor {
       ^
dshollman/rcu_ptr.hpp:109:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:128:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
1 warning and 3 errors generated.
make: *** [test1] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test4 test4.cpp -pthread -lurcu -lurcu-signal
In file included from test4.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from test4.cpp:3:
./rcu_guard.hpp:21:23: error: too few arguments to function call, expected 1, have 0; did you mean
      'rcu_flavor_struct::read_unlock'?
            this->rd->read_unlock();
                      ^~~~~~~~~~~
                      rcu_flavor_struct::read_unlock
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu-flavor.h:32:9: note: 'rcu_flavor_struct::read_unlock'
      declared here
        void (*read_unlock)(void);
               ^
1 warning and 1 error generated.
make: *** [test4] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test5 domains/test5.cpp -pthread -lurcu -lurcu-signal
In file included from domains/test5.cpp:4:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test6 imuerte/test6.cpp -pthread -lurcu -lurcu-signal
In file included from imuerte/test6.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_delete<foo, std::default_deleter<foo> >::retire(std::rcu_flavor_base&) in test6-b93140.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test6] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test7 intrusive/test7.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive/test7.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test8 intrusive2/test8.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive2/test8.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_ptr<foo>::retire(std::rcu_flavor_base&, void (*)(foo*)) in test8-f52e9f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test8] Error 1
make: Target `all' not remade because of errors.
Arthurs-MacBook-Pro-2:Test ajo$ make -k
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test1 dshollman/test1.cpp -pthread -lurcu -lurcu-signal
In file included from dshollman/test1.cpp:1:
In file included from dshollman/rcu_ptr.hpp:7:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:40:16: error: redefinition of 'is_rcu_flavor' as different kind of symbol
constexpr bool is_rcu_flavor = is_rcu_flavor<_T>::value;
               ^
dshollman/rcu_ptr.hpp:32:8: note: previous definition is here
struct is_rcu_flavor {
       ^
dshollman/rcu_ptr.hpp:109:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:128:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
1 warning and 3 errors generated.
make: *** [test1] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test4 test4.cpp -pthread -lurcu -lurcu-signal
In file included from test4.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from test4.cpp:3:
./rcu_guard.hpp:21:23: error: too few arguments to function call, expected 1, have 0; did you mean
      'rcu_flavor_struct::read_unlock'?
            this->rd->read_unlock();
                      ^~~~~~~~~~~
                      rcu_flavor_struct::read_unlock
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu-flavor.h:32:9: note: 'rcu_flavor_struct::read_unlock'
      declared here
        void (*read_unlock)(void);
               ^
1 warning and 1 error generated.
make: *** [test4] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test6 imuerte/test6.cpp -pthread -lurcu -lurcu-signal
In file included from imuerte/test6.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_delete<foo, std::default_deleter<foo> >::retire(std::rcu_flavor_base&) in test6-ff90ad.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test6] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test8 intrusive2/test8.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive2/test8.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_ptr<foo>::retire(std::rcu_flavor_base&, void (*)(foo*)) in test8-dee2e0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test8] Error 1
make: Target `all' not remade because of errors.
```

A few of these are trivial typos (e.g. typoing `rcu_flavor_base_v` as `rcu_flavor_base`, forgetting to `return 0` at the end of a function that apparently now needs to return 0 for some reason); but the linker errors seem like killers to me. It looks like polymorphic base class `rcu_domain` got changed into non-polymorphic base class `rcu_flavor_base` — and unfortunately "non-polymorphic base class" is an oxymoron. Where the old code made virtual calls to abstract methods, the new code is making concrete calls to methods that are simply undefined — hence, linker errors.

I suggest that we fix the tests simply by reverting f25b3a71e97438832837d4b4f25f3e5bc6d55675 and (especially) e9453e11432018d5599e725d825482c515bfd55f.

I'm willing to help out with the grunt work of what the Committee asked for, if you can point me at their commentary and/or just give me the executive summary. (And for some of their things, like apparently "no virtuals ever", I think you might just have to go back and tell them to suck it up. *But*, Lawrence Crowl's P0260R3 might have a nifty way to get the best of both worlds polymorphismwise via a sort of "DIY type erasure": see his [`queue_base` and `queue_wrapper`](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0260r1.html#Binary).

### PR DESCRIPTION
**Pull request by Quuxplusone**
And provide helpers `std::rcu::rcu_domain_base` and `std::rcu::rcu_domain_wrapper` following the example set by Lawrence Crowl's [P0260R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0260r0.html#Binary).

I believe this accomplishes the same goal as Paul's e9453e11432018d5599e725d825482c515bfd55f but without breaking any existing tests.

Notice that I've renamed `::std::rcu_bp` --> `::rcu_domain_bp` and so on. The move out of `namespace std` indicates that these classes are *not* being proposed for standardization. The renaming to include `_domain` in their class names is just for clarity.

Notice that I've moved `rcu_domain_base` into the `::std::rcu` namespace. This makes its fully qualified name a bit redundant; I'd like to propose removing the redundant `rcu_` from a whole lot of identifiers (e.g. `std::rcu::domain_base`, `std::rcu::obj_base` (although personally I prefer `std::rcu::enable_retire_on_this`), etc). That renaming would be too much for this PR, though.

Fixes #6.

### CODE REVIEW

File: Test/domains/urcu-bp.hpp [hunk 1]
```diff
@@ -3,22 +3,23 @@
 #include "rcu_domain.hpp"
 
 #include <urcu-bp.h>
-#define _LGPL_SOURCE
```
Comment (Quuxplusone) [inline Test/domains/urcu-bp.hpp:6]: In this branch I attempted to "fix" the preprocessor stuff here by moving `#define _LGPL_SOURCE` up above the `#include <urcu-bp.h>` that it's clearly supposed to affect; but when I did that, I got compiler errors like

```
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu/static/wfcqueue.h:384:10: error: cannot initialize return
      object of type 'struct cds_wfcq_node *' with an rvalue of type 'void *'
                return CDS_WFCQ_WOULDBLOCK;
                       ^~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu/wfcqueue.h:46:29: note: expanded from macro
      'CDS_WFCQ_WOULDBLOCK'
#define CDS_WFCQ_WOULDBLOCK     ((void *) -1UL)
                                ^~~~~~~~~~~~~~~
```

so I punted on that issue by just removing the useless `#define` lines.

File: Test/domains/urcu-bp.hpp [hunk 2]
```diff
@@ -3,22 +3,23 @@
...
+    void register_thread() { rcu_register_thread(); }
+    void unregister_thread() { rcu_unregister_thread(); }
+    void thread_offline() noexcept { rcu_thread_offline(); }
+    void thread_online() noexcept { rcu_thread_online(); }
 
-        static constexpr bool register_thread_needed() { return false; }
-    };
-} // namespace std
+    static constexpr bool quiescent_state_needed() { return false; }
+    void quiescent_state() noexcept { rcu_quiescent_state(); }
```
Comment (Quuxplusone) [inline Test/domains/urcu-bp.hpp]: @paulmck: maybe you can explain to me... I would have expected `quiescent_state()` to be a noop for any domain where `quiescent_state_needed() == false`. Is there some benefit to providing a non-noop `quiescent_state()` here?

Comment (paulmckrcu) [reply Test/domains/urcu-bp.hpp]: I was relying on the underlying userspace RCU implementation being a no-op.  I cannot immediately think of a reason to have a non-noop quiescent_state() if quiescent_state_needed() returns false, at least not other than statistics gathering and debugging.

But what did you have in mind?

Comment (Quuxplusone) [reply Test/domains/urcu-bp.hpp]: > what did you have in mind?

Definitely: replacing the body of this function with `{ }` for speed and for clarity (so that nobody else has to ask "why does this function have an effect, if it's explicitly not needed?").

Possibly: eliminating the requirement that RcuDomains implement a `quiescent_state` function at all, if they don't need one. The classically-polymorphic `rcu_domain_wrapper` could automatically fill in a no-op `void quiescent_state() noexcept override { }` for RcuDomains that don't provide such a function.

Possibly x2: eliminating `quiescent_state` from the generic RCU interface altogether. Consider a random user-defined type such as `rcu_domain_qsbr`. It can satisfy the RcuDomain concept *and also* provide a function `quiescent_state` that happens to trigger a cleanup cycle.

Comment (paulmckrcu) [reply Test/domains/urcu-bp.hpp]: The big requirement from my viewpoint is that a program that doesn't invoke quiescent_state can get warnings if it tries to use rcu_domain_qsbr.  It seems like that can be made to work with either of  your alternatives, for example, having an RcuDomainsQsbr concept (or similar).

From a pure C++ viewpoint, which is best?

Comment (Quuxplusone) [reply Test/domains/urcu-bp.hpp]: > a program that doesn't invoke quiescent_state can get warnings if it tries to use rcu_domain_qsbr

I don't understand your grammar there. Can you clarify?

Comment (paulmckrcu) [reply Test/domains/urcu-bp.hpp]: First, apologies for the delay -- the day job grabbed me by both ankles in several directions for quite some time.  But the pending Linux-kernel RCU commits greatly increased SRCU scalability and also do a net reduction of more than 2700 lines of code, so at least something useful came out of it...  And yes, had I been thinking at all at the time, I would have simply handed the C++ RCU reins over to you.

OK...  quiescent_state().  Suppose I have some code that doesn't care what flavor of RCU it is using.  If it happens to be using rcu_domain_qsbr, then that code absolutely must periodically invoke quiescent_state().  So either the code has be changed when the underlying RCU implementation switches to or from rcu_domain_qsbr, or it has to call quiescent_state() all the time, which means (as far as I know) that all domains must supply some sort of implementation, if only an empty function.

Does that help, or am I missing the point of your question?

Comment (Quuxplusone) [reply Test/domains/urcu-bp.hpp]: > replacing the body of this function with { } for speed and for clarity

@paulmckrcu: I've added a commit to this branch which I think illustrates this point: 105ed3e73cad5a005267e6fa3a7c5d67cc34efc8
Would that commit 105ed3e73cad5a005267e6fa3a7c5d67cc34efc8 be a good idea, or would it regress some useful behavior of the current code?

Comment (Quuxplusone) [reply Test/domains/urcu-bp.hpp]: > The classically-polymorphic rcu_domain_wrapper could automatically fill in a no-op `void quiescent_state() noexcept override { }` for RcuDomains that don't provide such a function.

I'll put this in a branch and link it here, just to show what it would look like. (Edit: [Here it is!](https://github.com/Quuxplusone/RCUCPPbindings/commit/bc91a116d4a59006f111afd9255313537ba1d73d)) The idea is to provide a sane default so that users (in this case, implementors of `rcu_domain_foo`) don't have to repeat boilerplate code that would just be the default.

A precedent in the Standard is how `allocator_traits<A>::construct` dispatches to `A::construct` iff it exists and to `::operator new` otherwise.

Comment (paulmckrcu) [reply Test/domains/urcu-bp.hpp]: Yes, if the RCU domain knows for sure that a given function is a no-op, then it should be plenty OK to avoid calling it.

And yes, I was in fact missing the bit about a sane default being supplied.  I don't see a problem with that approach.
