### ISSUE TITLE
Tests are broken by e9453e1

### ISSUE THREAD

**Issue by Quuxplusone** [paulmckrcu/RCUCPPbindings#6]
```
Arthurs-MacBook-Pro-2:Test ajo$ make -k
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test1 dshollman/test1.cpp -pthread -lurcu -lurcu-signal
In file included from dshollman/test1.cpp:1:
In file included from dshollman/rcu_ptr.hpp:7:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:40:16: error: redefinition of 'is_rcu_flavor' as different kind of symbol
constexpr bool is_rcu_flavor = is_rcu_flavor<_T>::value;
               ^
dshollman/rcu_ptr.hpp:32:8: note: previous definition is here
struct is_rcu_flavor {
       ^
dshollman/rcu_ptr.hpp:109:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:128:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
1 warning and 3 errors generated.
make: *** [test1] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test4 test4.cpp -pthread -lurcu -lurcu-signal
In file included from test4.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from test4.cpp:3:
./rcu_guard.hpp:21:23: error: too few arguments to function call, expected 1, have 0; did you mean
      'rcu_flavor_struct::read_unlock'?
            this->rd->read_unlock();
                      ^~~~~~~~~~~
                      rcu_flavor_struct::read_unlock
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu-flavor.h:32:9: note: 'rcu_flavor_struct::read_unlock'
      declared here
        void (*read_unlock)(void);
               ^
1 warning and 1 error generated.
make: *** [test4] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test5 domains/test5.cpp -pthread -lurcu -lurcu-signal
In file included from domains/test5.cpp:4:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test6 imuerte/test6.cpp -pthread -lurcu -lurcu-signal
In file included from imuerte/test6.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_delete<foo, std::default_deleter<foo> >::retire(std::rcu_flavor_base&) in test6-b93140.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test6] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test7 intrusive/test7.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive/test7.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test8 intrusive2/test8.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive2/test8.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_ptr<foo>::retire(std::rcu_flavor_base&, void (*)(foo*)) in test8-f52e9f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test8] Error 1
make: Target `all' not remade because of errors.
Arthurs-MacBook-Pro-2:Test ajo$ make -k
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test1 dshollman/test1.cpp -pthread -lurcu -lurcu-signal
In file included from dshollman/test1.cpp:1:
In file included from dshollman/rcu_ptr.hpp:7:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:40:16: error: redefinition of 'is_rcu_flavor' as different kind of symbol
constexpr bool is_rcu_flavor = is_rcu_flavor<_T>::value;
               ^
dshollman/rcu_ptr.hpp:32:8: note: previous definition is here
struct is_rcu_flavor {
       ^
dshollman/rcu_ptr.hpp:109:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from dshollman/test1.cpp:1:
dshollman/rcu_ptr.hpp:128:7: error: template argument for non-type template parameter must be an expression
      is_rcu_flavor<_RCUDomain>
      ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:244:16: note: 
      template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
1 warning and 3 errors generated.
make: *** [test1] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test4 test4.cpp -pthread -lurcu -lurcu-signal
In file included from test4.cpp:2:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
In file included from test4.cpp:3:
./rcu_guard.hpp:21:23: error: too few arguments to function call, expected 1, have 0; did you mean
      'rcu_flavor_struct::read_unlock'?
            this->rd->read_unlock();
                      ^~~~~~~~~~~
                      rcu_flavor_struct::read_unlock
/usr/local/Cellar/userspace-rcu/0.9.1/include/urcu-flavor.h:32:9: note: 'rcu_flavor_struct::read_unlock'
      declared here
        void (*read_unlock)(void);
               ^
1 warning and 1 error generated.
make: *** [test4] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test6 imuerte/test6.cpp -pthread -lurcu -lurcu-signal
In file included from imuerte/test6.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_delete<foo, std::default_deleter<foo> >::retire(std::rcu_flavor_base&) in test6-ff90ad.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test6] Error 1
c++ -g -std=c++1z -I/usr/local/Cellar/userspace-rcu/0.9.1/include -L/usr/local/Cellar/userspace-rcu/0.9.1/lib -Dthread_local= -I./domains -o test8 intrusive2/test8.cpp -pthread -lurcu -lurcu-signal
In file included from intrusive2/test8.cpp:3:
./domains/urcu-signal.hpp:14:58: warning: control reaches end of non-void function [-Wreturn-type]
        cookie_t read_lock() noexcept { rcu_read_lock(); }
                                                         ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "std::rcu_flavor_base::retire(rcu_head*, void (*)(rcu_head*))", referenced from:
      std::rcu_head_ptr<foo>::retire(std::rcu_flavor_base&, void (*)(foo*)) in test8-dee2e0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test8] Error 1
make: Target `all' not remade because of errors.
```

A few of these are trivial typos (e.g. typoing `rcu_flavor_base_v` as `rcu_flavor_base`, forgetting to `return 0` at the end of a function that apparently now needs to return 0 for some reason); but the linker errors seem like killers to me. It looks like polymorphic base class `rcu_domain` got changed into non-polymorphic base class `rcu_flavor_base` — and unfortunately "non-polymorphic base class" is an oxymoron. Where the old code made virtual calls to abstract methods, the new code is making concrete calls to methods that are simply undefined — hence, linker errors.

I suggest that we fix the tests simply by reverting f25b3a71e97438832837d4b4f25f3e5bc6d55675 and (especially) e9453e11432018d5599e725d825482c515bfd55f.

I'm willing to help out with the grunt work of what the Committee asked for, if you can point me at their commentary and/or just give me the executive summary. (And for some of their things, like apparently "no virtuals ever", I think you might just have to go back and tell them to suck it up. *But*, Lawrence Crowl's P0260R3 might have a nifty way to get the best of both worlds polymorphismwise via a sort of "DIY type erasure": see his [`queue_base` and `queue_wrapper`](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0260r1.html#Binary).

**Comment by Quuxplusone** [comment]
My #10 addresses the relevant Committee feedback AFAICT. I advise reverting f25b3a7 and e9453e1 and then applying my #10.
